--- #YAML:1.0
name:                Net-Squid-Auth-Plugin-UserList
version:             0.02
abstract:            A User List-Based Credentials Validation Plugin for L<Net::Squid::Auth::Engine>
license:             ~
author:              
    - Luis Motta Campos <lmc@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Temp:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
